export const descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Goofy',
    'Happy',
    'Virtual',
    'Muddy',
    'Sketchy',
    'Gorgeous',
    'Rootin\' Tootin\'',
    'Creepy',
    'Devil\'s',
  'Circle-C',
    'L-Bar-C',
    'Big',
    'Obnoxious',
    'Rickety',
    'Whackadoodle',
  'Rustic',
  'Scenic',
  'Tranquil',
  'Wooded',
  'Serene',
  'Cozy',
  'Family-friendly',
  'Peaceful',
  'Secluded',
  'Picturesque',
  'Campfire',
  'Natural',
  'Adventure',
  'Remote',
  'Bucolic',
  'Sunny',
  'Hiking',
  'Camping',
    'Relaxing',
    'WildWood',
    'Death',
    'Lost',
  'Enchanted'
];


export const places = [
  "Flats",
  "Village",
  "Canyon",
  "Pond",
  "Group Camp",
  "Horse Camp",
  "Ghost Town",
  "Camp",
  "Dispersed Camp",
  "Backcountry",
  "River",
  "Creek",
  "Creekside",
  "Bay",
  "Spring",
  "Bayshore",
  "Sands",
  "Mule Camp",
  "Hunting Camp",
  "Cliffs",
  "Hollow",
  "Forest",
  "Lake",
  "Town",
  "Reformatory",
  "Stone",
  "Ranch",
  "Butte",
  "Wilderness",
  "Campground",
  "Shores",
  "Family Campground",
  "Cabins",
  "Resort",
  "Mountain",
  "Hill",
  "Fronds",
  "Day Camp Area",
  "RV Camp",
  "Scout Camp",
  "Muffin-eating Camp",
  "Boot Camp",
  "Day Spa",
  "Place",
  "National Park",
  "State Park",
  "Ridge",
  "Hole",
    "Children's Camp",
    "Commune",
    "Campsite"
];

export const adjectives = [
    'Serene',
    'Picturesque',
    'Idyllic',
    'Lush',
    'Remote',
    'Contemporary',
    'Rustic',
    'Cosmopolitan',
    'Tranquil',
    'Architectural',
    'Enchanting',
    'Atmospheric',
    'Secluded',
    'Inviting',
    'Eclectic',
    'Mystical',
    'Opulent',
    'Timeless',
    'Exotic',
    'Artistic',
    'Cultural',
    'Cozy',
    'Soothing',
    'Panoramic',
    'Mesmerizing',
    'Nostalgic',
    'Wowy',
    'Luxurious',
    'Serendipitous',
    'Inspiring',
    'Dynamic',
    'Verdant',
    'Sacred',
    'Dreamy',
    'Charming',
    'Whimsical',
    'Ethereal',
    'Surreal',
    'Festive',
    'Breathtaking',
    'Unspoiled',
    'ridiculous',
    'boring',
    'abomidable',
    'hellish',
    'putrid',
    'maniacal',
    'horrific',
    'lousy',
    'disgusting',
    'ghastly',
    'scandalous',
    'sleazy',
    'questionable',
    'wibbly-wobbly',
    'squonchy',
    'unappealing',
    'decent',
    'unquestionably real',
    'questionable',
    'gorgeous',
    'wonderful',
    'awe-inspiring',
    'godly',
    'unbelievable',
  'Tranquil',
  'Enchanted',
  'Luminous',
  'Whimsical',
  'Enigmatic',
  'Majestic',
  'Harmonious',
  'Serene',
  'Vibrant',
  'Ethereal',
  'Verdant',
  'Mystical',
  'Radiant',
  'Captivating',
  'Quaint',
  'Ponderous',
  'Serendipitous',
  'Pristine',
  'Resplendent',
  'Breathtaking',
  'Idyllic',
  'Mesmerizing',
  'Exquisite',
  'Ornate',
  'Picturesque',
  'Splendid',
  'Awe-inspiring',
  'Bewitching',
  'Enveloping',
  'Delicate',
  'Winsome',
  'Enraptured',
  'Uplifting',
  'Scenic',
  'Charming',
  'Paradisiacal',
  'Fascinating',
  'Euphoric',
  'Spellbinding',
  'Lovely',
  'Sublime',
  'Magnificent',
  'Delightful',
  'Blissful',
  'Splendiferous',
  'Ponderous',
  'Exquisite',
  'Ornate',
  'Lovely'
];

export const nouns = [
    'Arroyo',
    'Badland',
    'Barrier Island',
    'Basin',
    'Bay',
    'Butte',
    'Canal',
    'Canyon',
    'Cape',
    'Cave',
    'Channel',
    'Cliff',
    'Cove',
    'Crater Lake',
    'Crevasse',
    'Dam',
    'Dell',
    'Delta',
    'Desert',
    'Divide',
    'Dome',
    'Dry Lake',
    'Dune',
    'fjord',
    'Floodplain',
    'Forest',
    'Glacier',
    'Gully',
    'Gulf',
    'Gorge',
    'hill',
    'Hoodoo',
    'Iceberg',
    'Inlet',
    'Island',
    'Islet',
    'Lake',
    'Lowland',
    'Marsh',
    'Mesa',
    'Mountain',
    'Oasis',
    'Ocean',
    'Rapids',
    'Ravine',
    'River',
    'Sandbar',
    'Sinkhole',
    'Swamp',
    'Volcano',
    'Waterfall',
    'Donkey',
    'Bologna sandwich',
    'Stone',
    'Formation',
    'Tree',
    'Meadow',
    'Dirt Pit',
    'Bear',
    'blade of grass',
    'view',
  'Brook',
  'Creek',
  'Estuary',
  'Grove',
  'Harbor',
  'Hollow',
  'Lagoon',
  'Meadow',
  'Pond',
  'Rainforest',
  'Reef',
  'Savanna',
  'Slope',
  'Spring',
  'Summit',
  'Thicket',
  'Valley',
  'Wetland',
  'Woodland',
  'Plateau',
  'Claypan',
  'Headland',
  'Ridge',
  'Hillside',
  'Foothill',
  'Tundra',
  'Grassland',
  'Cavern',
  'Bayou',
]